### ISSUE TITLE
Database connection

### ISSUE THREAD

**Issue by muromeo1** [Pluvie/hanami-mongoid#1]
Hey dude, how can I use my `mongoid.yml` to setup my database connection using this gem?

**Comment by Pluvie** [comment]
Hi, you need to add an `initializer`.
Look at Hanami docs here: [https://guides.hanamirb.org/projects/initializers/](https://guides.hanamirb.org/projects/initializers/)

So, for example, add a file called `mongoid.rb` under `config/initializers` with this code:
```ruby
Mongoid.load! File.join(__dir__, "../mongoid.yml"), ENV["HANAMI_ENV"]
```
This assumes that you've put your `mongoid.yml` file under `config/`.
